---
version: '2'
services:
  zookeeper-dc1:
    image: ${REPOSITORY}/cp-zookeeper:${CONFLUENT_DOCKER_TAG}
    hostname: zookeeper-dc1
    container_name: zookeeper-dc1
    ports:
      - "2181:2181"
      - "9997:9997"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./zookeeper/1/data:/var/lib/zookeeper/data
      - ./zookeeper/1/log:/var/lib/zookeeper/log
      - ./zookeeper/1/zookeeper.properties:/etc/kafka/zookeeper.properties

  zookeeper-dc2:
    image: ${REPOSITORY}/cp-zookeeper:${CONFLUENT_DOCKER_TAG}
    hostname: zookeeper-dc2
    container_name: zookeeper-dc2
    ports:
      - "2182:2181"
      - "9998:9998"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./zookeeper/2/data:/var/lib/zookeeper/data
      - ./zookeeper/2/log:/var/lib/zookeeper/log
      - ./zookeeper/2/zookeeper.properties:/etc/kafka/zookeeper.properties

  broker-dc1:
    image: ${REPOSITORY}/cp-kafka:${CONFLUENT_DOCKER_TAG}
    hostname: broker-dc1
    container_name: broker-dc1
    depends_on:
      - zookeeper-dc1
      - zookeeper-dc2
    ports:
      - "9091:9091"
      - "9991:9991"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-dc1:2181,zookeeper-dc2:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-dc1:29091,PLAINTEXT_HOST://localhost:9091
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    volumes:
      - ./broker/1/data:/var/lib/kafka/data

  broker-dc2:
    image: ${REPOSITORY}/cp-kafka:${CONFLUENT_DOCKER_TAG}
    hostname: broker-dc2
    container_name: broker-dc2
    depends_on:
      - zookeeper-dc1
    ports:
      - "9092:9092"
      - "9992:9992"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-dc1:2181,zookeeper-dc2:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-dc2:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    volumes:
      - ./broker/2/data:/var/lib/kafka/data

  broker-dc3:
    image: ${REPOSITORY}/cp-kafka:${CONFLUENT_DOCKER_TAG}
    hostname: broker-dc3
    container_name: broker-dc3
    depends_on:
      - zookeeper-dc1
      - zookeeper-dc2
    ports:
      - "9093:9093"
      - "9993:9993"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-dc1:2181,zookeeper-dc2:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-dc3:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    volumes:
      - ./broker/3/data:/var/lib/kafka/data


  datagen-dc1-topic1:
    image: confluentinc/cp-kafka:${CONFLUENT_DOCKER_TAG}
    hostname: datagen-dc1-topic1
    container_name: datagen-dc1-topic1
    depends_on:
      - broker-dc1
      - broker-dc2
      - broker-dc3
    command: >
      bash -c '
      echo "Waiting for Kafka to be ready..." &&
      cub kafka-ready -b broker-dc1:29091,broker-dc2:29092,broker-dc3:29093 3 90 &&
      echo "Creating topics..." &&
      kafka-topics --create --topic topic1 --bootstrap-server broker-dc1:29091 --partitions 3 --replication-factor 2 --if-not-exists &&
      kafka-topics --create --topic topic2 --bootstrap-server broker-dc2:29092 --partitions 3 --replication-factor 2 --if-not-exists &&
      kafka-topics --create --topic topic3 --bootstrap-server broker-dc3:29093 --partitions 3 --replication-factor 2 --if-not-exists &&
      echo "Sending messages to topics every 10 seconds..." &&
      while true; do
        MESSAGE="Current date: $(date)"
        echo "$MESSAGE" | kafka-console-producer --topic topic1 --bootstrap-server broker-dc1:29091,broker-dc2:29092,broker-dc3:29093
        echo "Sent to topic1: $MESSAGE"
        echo "$MESSAGE" | kafka-console-producer --topic topic2 --bootstrap-server broker-dc1:29091,broker-dc2:29092,broker-dc3:29093
        echo "Sent to topic2: $MESSAGE"
        echo "$MESSAGE" | kafka-console-producer --topic topic3 --bootstrap-server broker-dc1:29091,broker-dc2:29092,broker-dc3:29093
        echo "Sent to topic3: $MESSAGE"
        sleep 10
      done'



  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8089:8080
    depends_on:
      - broker-dc1
      - broker-dc2
      - broker-dc3
      - zookeeper-dc1
      - zookeeper-dc2
    environment:
      KAFKA_CLUSTERS_0_NAME: DHL
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker-dc1:29091,broker-dc2:29092,broker-dc3:29093
      DYNAMIC_CONFIG_ENABLED: 'true'
      SERVER_SERVLET_CONTEXT_PATH: /kafka-ui

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v3.10.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 8080

  dozzle_nginx:
    image: ronaldschouw/nginx
    container_name: dozzle_nginx
    ports:
      - 9999:9999
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf:cached
